# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [77]:

import numpy as np

ar=np.random.randint(1,20,size=(5,5))
print(ar)

ar[2,:]=1

print(ar)



[[12  3  5 14 12]
 [18  9 10 11  3]
 [ 5 18  4  2  9]
 [11 15  5  3 13]
 [17  1 19 14 11]]
[[12  3  5 14 12]
 [18  9 10 11  3]
 [ 1  1  1  1  1]
 [11 15  5  3 13]
 [17  1 19 14 11]]


In [78]:
arr=np.random.randint(1,16,size=(4,4))
print(arr)

np.fill_diagonal(arr,0)
print(arr)


[[ 1 15  7 13]
 [ 1  5 13  3]
 [12  7 10 14]
 [12 14 10  9]]
[[ 0 15  7 13]
 [ 1  0 13  3]
 [12  7  0 14]
 [12 14 10  0]]


In [79]:

arr=np.arange(1,37).reshape(6,6)

print(arr)

ar=arr[2:5,1:4]

print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [80]:
arr=np.random.randint(1,25,size=(5,5))

print(arr)

border=np.concatenate((arr[:,0], arr[4,1:], arr[1:-1,-1],arr[0,:]))

print(border)
array=arr
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

[[ 3  5 16  6 17]
 [18 12 11  8 19]
 [19  5 23 11 20]
 [ 1 10  2 20 15]
 [ 9  8  3 16 14]]
[ 3 18 19  1  9  8  3 16 14 19 20 15  3  5 16  6 17]
Border elements:
[ 3  5 16  6 17  9  8  3 16 14 18 19  1 19 20 15]


In [81]:
ar1=np.arange(1,13).reshape(3,4)

ar2=np.random.randint(1,12,size=(3,4))

ar3=ar1> ar2

print(ar3)


[[False False False  True]
 [False  True False  True]
 [ True False  True  True]]


In [62]:
ar1=np.arange(1,17).reshape(4,4)
print(ar1)
rsum=ar1.sum(1)
print(rsum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]


In [84]:
arr=np.random.randint(1,25,size=(5,5))

print(arr)

m=np.mean(arr)
sd=np.std(arr)

arr1=(arr-m)/sd

print(arr1.mean())

[[ 1  9 17 18 18]
 [ 3 11 10 12 16]
 [17 20  2  2 12]
 [14  4 18 18  1]
 [ 7 24 19 15 16]]
-2.2204460492503132e-17


In [ ]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array - row_array
print("Resulting array:")
print(result)

Original array:
[[ 9 10  4]
 [ 1  2  5]
 [ 2  4  1]]
1D array:
[1 3 4]
Resulting array:
[[ 8  7  0]
 [ 0 -1  1]
 [ 1  1 -3]]


In [89]:
array = np.random.randint(1, 11, size=(3, 3))

arr=np.linalg.eigvals(array)
print(arr)

[14.56999404  0.96546548 -7.53545952]


In [93]:
array = np.arange(1, 10).reshape(3, 3)

print(array)

ar=array.reshape(9,1)

print(ar)

arr=array.flatten()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [94]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[20 12 13 20  5]
 [12 19  2  3 17]
 [18  4 10  1 18]
 [18 18  1  4 15]
 [17  7  6 12  9]]
Corner elements:
[20  5 17  9]


In [95]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

array[array>10]=-22

print(array)

Original array:
[[15 15 19  4  7]
 [14 17  5  8  8]
 [16 17 14  8 20]
 [ 4  9 17  5  5]
 [11 15  9 11 15]]
[[-22 -22 -22   4   7]
 [-22 -22   5   8   8]
 [-22 -22 -22   8 -22]
 [  4   9 -22   5   5]
 [-22 -22   9 -22 -22]]


In [96]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [97]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [99]:
import numpy.ma as ma
# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 15)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[20 19  9  8]
 [ 6  8 11 14]
 [ 2 11  3 15]
 [ 6 15  7 12]]
Masked array:
[[-- -- 9 8]
 [6 8 11 14]
 [2 11 3 15]
 [6 15 7 12]]
Sum of unmasked elements: 127


In [100]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 9 11 12]
 [17 17 19]
 [17  7 20]]
Masked array:
[[-- 11 12]
 [17 -- 19]
 [17 7 --]]
Modified masked array:
[[13 11 12]
 [17 13 19]
 [17  7 13]]
